import { Injectable, inject } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { AgentContext } from '../models/agent-context.model';
import { WorkflowExecutorService } from '../execution/workflow-executor.service';
import { GeminiService } from '../../services/gemini.service';

@Injectable({
  providedIn: 'root'
})
export class AgentRuntimeService {

  private readonly workflowExecutor =
    inject(WorkflowExecutorService);

  private readonly geminiService =
    inject(GeminiService);

  async execute(
    ticket: any,
    onStep?: (message: string) => void
  ): Promise<AgentContext> {

    const context: AgentContext = {
      ticket,
      executionLog: [],
      onStep
    };

    context.executionLog.push(
      'Agent Runtime Started'
    );

    context.onStep?.(
      '🧠 Planning workflow'
    );

    const result: any =
      await firstValueFrom(
        this.geminiService.analyze(
          ticket.subject,
          ticket.description
        )
      );

    let agentResponse =
      result.agentResponse;

    agentResponse = agentResponse
      .replace(/```json/g, '')
      .replace(/```/g, '')
      .trim();

    const parsed =
      JSON.parse(agentResponse);

    context.workflow =
      parsed.workflow;

    context.decision =
      parsed.decision;

    context.executionLog.push(
      'Workflow generated by AI'
    );

    context.onStep?.(
      '✅ Workflow generated'
    );

    await this.workflowExecutor.execute(
      context
    );

    context.executionLog.push(
      'Agent Runtime Completed'
    );

    context.onStep?.(
      '🎉 AI analysis completed'
    );

    return context;

  }

}