import { Injectable, inject } from '@angular/core';
import { firstValueFrom } from 'rxjs';
import { Ticket } from '../models/ticket.model';
import { AiResponse } from '../models/ai-response.model';
import { CategorizationTool } from '../agent-tools/categorization.tool';
import { PriorityTool } from '../agent-tools/priority.tool';
import { AssignmentTool } from '../agent-tools/assignment.tool';
import { SimilarityTool } from '../agent-tools/similarity.tool';
import { GeminiService } from './gemini.service';
@Injectable({
    providedIn: 'root'
})
export class AiAgentService {
    private readonly categorizationTool =
        inject(CategorizationTool);
    private readonly priorityTool =
        inject(PriorityTool);
    private readonly assignmentTool =
        inject(AssignmentTool);
    private readonly similarityTool =
        inject(SimilarityTool);
    private readonly geminiService =
        inject(GeminiService);
    async analyzeTicket(
        ticket: Ticket,
        allTickets: Ticket[]
    ): Promise<AiResponse> {
        // Step 1 - Categorize
        const category =
            this.categorizationTool.categorize(
                ticket.subject,
                ticket.description
            );
        // Step 2 - Priority
        const priority =
            this.priorityTool.assignPriority(
                ticket.subject,
                ticket.description
            );
        // Step 3 - Team Assignment
        const assignedTeam =
            this.assignmentTool.assignTeam(
                category
            );
        // Step 4 - Similar Tickets
        const similarTickets =
            this.similarityTool.findSimilarTickets(
                ticket,
                allTickets
            );
        // Step 5 - Gemini Reasoning
        const geminiResponse =
            await firstValueFrom(
                this.geminiService.analyzeTicket(
                    ticket.subject,
                    ticket.description,
                    category,
                    priority,
                    assignedTeam,
                    similarTickets
                )
            );
        return {
            category,
            priority,
            assignedTeam,
            similarTickets,
            rootCause:
                'Generated by Gemini AI',
            resolution: [
                'See Gemini Recommendation'
            ],
            escalation:
                priority === 'High',
            aiRecommendation:
                geminiResponse.response
        };
    }
}
